name: SwiftLint

on:
  pull_request:
  push:
  workflow_dispatch:
  workflow_call:

jobs:
  SwiftLint:
    runs-on: [self-hosted, macOS] # ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: GitHub Action for SwiftLint
        run: swiftlint --reporter github-actions-logging --strict
